# Generated by Django 4.1.5 on 2023-04-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_layoutdata_remove_thresholds_user_thresholds_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholds',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
