# Generated by Django 4.1.5 on 2023-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_thresholds_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholds',
            name='temperature_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='temperature_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='voltage_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='voltage_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
