# Generated by Django 4.1.5 on 2023-04-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_thresholds_temperature_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thresholds',
            old_name='user_id',
            new_name='user',
        ),
    ]
