# Generated by Django 4.1.5 on 2023-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_user_id_thresholds_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholds',
            name='predicted_voltage_max',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thresholds',
            name='predicted_voltage_min',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
