# Generated by Django 4.1.5 on 2023-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_thresholds_predicted_voltage_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholds',
            name='predicted_voltage_max',
        ),
        migrations.RemoveField(
            model_name='thresholds',
            name='predicted_voltage_min',
        ),
        migrations.RemoveField(
            model_name='thresholds',
            name='voltage_max',
        ),
        migrations.RemoveField(
            model_name='thresholds',
            name='voltage_min',
        ),
        migrations.AddField(
            model_name='thresholds',
            name='power_max',
            field=models.DecimalField(decimal_places=1, default='20.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='thresholds',
            name='power_min',
            field=models.DecimalField(decimal_places=1, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='temperature_max',
            field=models.DecimalField(decimal_places=1, default='30.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='thresholds',
            name='temperature_min',
            field=models.DecimalField(decimal_places=1, default='0.00', max_digits=5),
        ),
    ]
